### ISSUE TITLE
Plugin Issue

### ISSUE THREAD

**Issue by jchrislemmer** [justinticktock/network-subsite-user-registration#3]
Hey there,

I think there might be a bug in the  plugin.

So, on line 388 of network-subsite-user-registration.php we have this:

`switch_to_blog( $result['blog_id'] );`

I am receiving the following error when using the plugin:

`2018/09/05 12:42:28 [error] 140434#0: *2150820 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /var/www/vhosts/my-sub-site-url/my-network-site-path/wp-content/plugins/network-subsite-user-registration/network-subsite-user-registration.php:388
Stack trace:
#0 /var/www/vhosts/my-sub-site-url/my-network-site-path/wp-includes/class-wp-hook.php(286): NSUR->switch_to_subsite_locale('')
#1 /var/www/vhosts/my-sub-site-url/my-network-site-path/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(false, Array)
#2 /var/www/vhosts/my-sub-site-url/my-network-site-path/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /var/www/vhosts/my-sub-site-url/my-network-site-path/wp-activate.php(34): do_action('activate_header')
#4 {main}
  thrown in /var/www/vhosts/my-sub-site-url/my-network-site-path/wp-content/plugins/network-subsite-user-registration/network-subsite-user-registration.php on line 388" while reading response header from upstream, client: 10.0.11.14, server: my-sub-site-url, request: "GET /wp-activate.php HTTP/1.1", upstream: "fastcgi://unix:///var/www/vhosts/system/my-sub-site-url/php-fpm.sock:", host: "www.my-sub-site-url"`

I think the main issue is with `Cannot use object of type WP_Error as array in /var/www/vhosts/my-sub-site-url/my-network-site-path/wp-content/plugins/network-subsite-user-registration/network-subsite-user-registration.php:388`

The blog_ID isn't being passed in the array?

Thanks
Chris

**Comment by justinticktock** [comment]
Hi Chris, I'm travelling at the moment so can't look into it for a few weeks.  My first suggestion would be to turn off WooCommerce and other plugins to see if it throws the same error during registration.

one other question ....is this on a subsite or the main site that you are registering a user account?

**Comment by jchrislemmer** [comment]
Hey Justin,

The issue is with WooCommerce.

I tested on a network UAT site. The moment I enable WooCommerce, it breaks the plugin.

I think it has to do with the way WooCommerce handles its user registrations. I'm not that good with PHP, so I doubt I'll be able to figure it out. However, I'll give it a shot at least.

Kind Regards
Chris
